/**
 * N-CEDI — useSupabase
 *
 * Typed wrapper around `@nuxtjs/supabase` that surfaces a Supabase
 * client pre-configured with our Database type.
 *
 * Usage (client-side composables / pages):
 *   const { client } = useSupabase()
 *   const { data } = await client.from('programs').select('*')
 *
 * The Database type is generated by `supabase gen types typescript`
 * and should live at `~/types/database.ts`.  Until it is generated
 * we fall back to a generic `Record<string, unknown>` so the rest of
 * the codebase can compile.
 */

import type { SupabaseClient } from '@supabase/supabase-js'

/**
 * When `supabase gen types typescript --local > app/types/database.ts`
 * has been run, replace this alias with a proper import:
 *
 *   import type { Database } from '~/types/database'
 *
 * Until then, the generic fallback keeps everything compiling.
 */
type Database = Record<string, unknown>

export function useSupabase() {
  const client = useSupabaseClient<Database>() as SupabaseClient<Database>
  return { client }
}
